<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Luxury Project Management</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
        }
        header {
            background: linear-gradient(to right, #004c97, #00a3e0);
            color: white;
            padding: 20px;
            text-align: center;
        }
        nav {
            display: flex;
            justify-content: center;
            background: #f4f4f4;
            padding: 10px;
        }
        nav a {
            margin: 0 15px;
            text-decoration: none;
            color: #004c97;
            font-weight: bold;
        }
        section {
            padding: 20px;
            max-width: 1200px;
            margin: auto;
        }
        .hero {
            background: url('luxury-project.jpg') no-repeat center center/cover;
            height: 400px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: white;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.7);
            text-align: center;
        }
        .hero h1 {
            font-size: 3rem;
        }
        .services {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: space-around;
        }
        .service {
            flex: 1 1 30%;
            background: #f9f9f9;
            padding: 15px;
            border: 1px solid #ddd;
            border-radius: 8px;
            text-align: center;
        }
        .service h3 {
            color: #004c97;
        }
        footer {
            background: #004c97;
            color: white;
            text-align: center;
            padding: 10px;
        }
        footer a {
            color: #00a3e0;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <header>
        <h1>Luxury Project Management</h1>
        <p>Elite Services for Discerning Clients</p>
    </header>
    <nav>
        <a href="#about">About</a>
        <a href="#services">Services</a>
        <a href="#portfolio">Portfolio</a>
        <a href="#contact">Contact</a>
    </nav>
    <section class="hero">
        <h1>Luxury Projects. Managed to Perfection.</h1>
    </section>
    <section id="about">
        <h2>About Us</h2>
        <p>At [Your Business Name], we specialize in providing tailored project management services for luxury ventures. Our expertise ensures that every detail of your project is meticulously planned and executed to perfection.</p>
    </section>
    <section id="services">
        <h2>Our Services</h2>
        <div class="services">
            <div class="service">
                <h3>Project Concierge</h3>
                <p>End-to-end high-touch project management services.</p>
            </div>
            <div class="service">
                <h3>Proposal Writing</h3>
                <p>Compelling project proposals tailored for funding and approvals.</p>
            </div>
            <div class="service">
                <h3>Luxury Property Consulting</h3>
                <p>Expert guidance for high-end real estate developments.</p>
            </div>
        </div>
    </section>
    <section id="portfolio">
        <h2>Portfolio</h2>
        <p>Coming Soon: Showcase of our luxury project achievements.</p>
    </section>
    <section id="contact">
        <h2>Contact Us</h2>
        <p>Let’s discuss your vision. Contact us today to schedule a consultation.</p>
        <p>Email: <a href="mailto:ismaeldaffar@gmail.com">ismaeldaffar@gmail.com</a></p>
        <p>Phone: <a href="tel:+962791539229">+962791539229</a></p>
    </section>
    <footer>
        <p>&copy; 2024 Luxury Project Management | Designed with excellence</p>
    </footer>
</body>
</html>
